collections:
  - name: "markdown"
    label: "Markdown"
    folder: "/src/markdown"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Filename", name: "filename", widget: "hidden", default: ""}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "bios"
    label: "Bios"
    folder: "/src/markdown/bios"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Filename", name: "filename", widget: "hidden", default: ""}
      - {label: "Body", name: "body", widget: "markdown"}